POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikdyb290IiwiaWQiOiI1Zjg4YWY4MmFjMzI5OTExMDEyZDQ1MzQiLCJpYXQiOjE2MTI0NTkyNzB9.CPtYrZ5FGqn7vIHeQMkTUlgk6ufthefxKnhsC3t1_TM

{
    "title": "Boop",
    "author": "Groot",
    "url": "https://fullstackopen.com/en/",
    "likes": "1"
}

# POST http://localhost:3003/api/blogs
# Content-Type: application/json

# {
#     "title": "Full Stack Open 2020",
#     "author": "Matti Luukkainen",
#     "url": "https://fullstackopen.com/en/",
#     "likes": "1",
#     "userId": "5f8780d42a4abe0905dc7297"
# }